config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'

  resources :tasks do 
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:destroy]

  # route for fetch
  patch "change_task_status", to: "tasks#change_task_status"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  has_one_attached :comment_file
  validates :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  validates :description, presence: true
  validates :deadline, presence: true
  validates :priority, presence: true

  # include PgSearch::Model 

  # pg_search_scope :filter_by_priority,
  # against: [ :priority ],
  # using: {
  #   tsearch: { prefix: true }
  # }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :comments, through: :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    authorize @comment
  end

  def create
    @comment = Comment.create(comment_params)
    @comment.task = Task.find(params[:task_id])
    authorize @comment
    puts @comment.comment_file
    if @comment.save
      respond_to do |format|
        format.html { redirect_to tasks_path(@comment.task_id) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js { render :comment_error}
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    authorize @comment
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private 

  def comment_params
    params.require(:comment).permit(:id, :content, :task_id, :comment_file)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :show, :destroy]

  def show
    authorize @task
  end

  def index
    @tasks = policy_scope(Task).order(done: :asc, priority: :asc, deadline: :asc, updated_at: :desc)
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize @task

    if @task.save
      redirect_to tasks_path
    else
      respond_to do |format|
        format.html { render :new }
        format.js { render :task_error_create }
      end
    end
  end

  def edit
    authorize @task
  end

  def update
    authorize @task
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to task_path(@task) }
        format.js { :update} 
      end
    else 
      respond_to do |format|
        format.html { render :edit }
        format.js { render :task_error_update }
      end
    end
  end

  def destroy
    @task.delete
    authorize @task
    redirect_to tasks_path
  end

  def change_task_status
    @task = Task.find(params[:id].to_i)
    authorize @task
    @task.done = !@task.done
    @task.save
  end

  private 

  def task_params
    params.require(:task).permit(:id, :description, :deadline, :priority, :done)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%d %B %Y")
  end
end

app/helpers/task_helper.rb
module TaskHelper

  def order_by_date(comments)
    comments.order(created_at: :asc)
  end

  def priority_in_word(priority)
    case priority
      when 1
        "High"
      when 2
        "Medium"
      when 3
        "Low"
    end
  end

  def tasks_due_today
    return Task.where(deadline: Date.today, done: false, user: current_user).size
  end

  def tasks_not_done
    return Task.where(done: false, user: current_user).size
  end

  def order_comments(array)
    return array.sort_by{ |element| element.created_at }
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <p class="small"><%= comment.content %></p>
  <div class="comment-details">
    <% if comment.comment_file.attached? %>
      <%= link_to url_for(comment.comment_file), 
                  target: "_blank"  do %>
                    <i class="fas fa-file-alt"></i>
                  <% end %>
    <% end %>
    <div class="comment-date">
      <p class="small"><%= format_date(comment.created_at) %></p>
      <%= link_to comment_path(comment),
                  method: :delete,
                  remote: true,
                  :data => { :confirm => "Are you sure you want to delete your comment ?" } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
  </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div>
  <%= simple_form_for([task, comment], remote: true) do |f| %>
  <div class="form-group mb-0">
    <%= f.input :content, label: false, placeholder: "Add a new comment", class:"form-control" %>
    <div class="custom-file">
    <%= f.input :comment_file, as: :file, label: false, class:"custom-file-label"%>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary mt-2" %>
  <% end %>
  </div>
</div>

app/views/comments/comment_error.js.erb
<%#= insert error message if an input is missing %>
var taskId = "<%= @comment.task_id %>";
var commentSelector = `#task-${taskId} .comments-cont`;
var errorMessageSelector = `#task-${taskId} .error-message`;
var errorMessageExist = document.querySelector(errorMessageSelector);

if (!errorMessageExist) {
  const errorMessage = '<p class="strong error-message mt-2">Content can not be blank.</p>';
  var formCont = document.querySelector(commentSelector);
  formCont.insertAdjacentHTML("beforeend", errorMessage);
}

app/views/comments/create.js.erb
var taskId = "<%= @comment.task_id %>";
var commentSelector = `#task-${taskId} .comments`;
var inputSelector = `#task-${taskId} #comment_content`;
var noCommentSelector = `#task-${taskId} .no-comment`;

function addComment(comment) {
  <%# delete "no comment yet"  %>
  const noComment = document.querySelector(noCommentSelector);
  if (noComment) {
    noComment.classList.add("d-none");
  }

  <%# add the comment after the existing comments  %>
  const commentsCont = document.querySelector(commentSelector);
  commentsCont.insertAdjacentHTML('beforeend', comment);
}

<%# clear the input form  %>
function clearInput() {
const inputField = document.querySelector(inputSelector);
  inputField.value = "";
}

addComment('<%= j render "comments/comment", comment: @comment %>');
clearInput();

app/views/comments/destroy.js.erb
  document.querySelector("#comment-<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoPoulpe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to tasks_path, class: "navbar-brand" do %>
    <%= image_tag "poulpe_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


  

app/views/tasks/_edit_task_form.html.erb
<div class="form-group card">
  <i class="fas fa-times text-right"></i>
  <%= simple_form_for(task, remote: true) do |f| %>
  <div class="">
    <%= f.input :description, label: "Task description", class:"form-control" %>
  </div>
    <div class="form-row d-flex justify-content-between">
      <div class="col-auto">
        <%= f.input :deadline, label: "Deadline", as: :date, html5: true, class:"form-control" %>
      </div>
      <div class="col-auto">
        <%= f.input :priority, as: :radio_buttons, collection: [["High", 1 ] , ["Medium", 2], ["Low", 3]], class:"form-control", wrapper: :vertical_collection_inline %>
      </div>
      <div class="col-auto mt-3 ml-4">
        <%= f.submit "Update", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
  <div class="main-content">
    <div class="cont-left">
      <div class="task-status">
        <% if task.done %>
          <i class="fas fa-check-circle done" data-id="<%= task.id %>"></i>
        <% else %>
          <i class="fas fa-times-circle in-progress" data-id="<%= task.id %>"></i>
        <% end %>
        <p class="strong"><%= task.description %></p>
      </div>
      <p class="small">Priority: <span class="strong priority-<%= task.priority %>"><%= priority_in_word(task.priority) %></span></p>
    </div>
    <div class="cont-right">
      <div class="deadline">
        <i class="far fa-clock "></i> <span class="small <%= "priority-1 strong" if task.deadline <= Date.today %> "><%= format_date(task.deadline) %></span>
      </div>
      <div class="actions">
        <div class="edit">
          <i class="fas fa-pen"></i>
        </div>
        <div class="delete">
        <%= link_to task_path(task),
                  method: :delete,
                  remote: true,
                  :data => { :confirm => "Are you sure you want to delete the task '#{task.description}' ?" } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
        </div>
        <div class="comment-icon">
          <i class="fas fa-comment-alt"></i> <%= task.comments.size %>
        </div>
      </div>
    </div>
  </div>
  <div class="edit-form d-none">
    <%= render "tasks/edit_task_form", task: task %>
  </div>
  <div class="comments-cont d-none card">
    <div class="comments">
    <% if task.comments.empty? %>
      <p class="small no-comment">No comment yet</p>
    <% end %>
      <% order_comments(task.comments).each do |comment| %>
        <% if policy(Comment).create?  %>
          <%= render "comments/comment", comment: comment %>
        <% end %>
      <% end %>
    </div>
    <div class="comments-form">
      <%= render "comments/comment_form", task: task, comment: Comment.new %>
    </div>
  </div>
  <i class="fas fa-sort-down text-center"></i>

app/views/tasks/_task_form.html.erb
<div class="form-group card">
<i class="fas fa-times text-right"></i>
  <%= simple_form_for(Task.new, remote: true) do |f| %>
  <div class="">
    <%= f.input :description, label: "Task description", class:"form-control" %>
  </div>
    <div class="form-row d-flex justify-content-between">
      <div class="col-auto">
        <%= f.input :deadline, label: "Deadline", as: :date, html5: true, class:"form-control" %>
      </div>
      <div class="col-auto">
        <%= f.input :priority, as: :radio_buttons, collection: [["High", 1 ] , ["Medium", 2], ["Low", 3]], class:"form-control", wrapper: :vertical_collection_inline %>
      </div>
      <div class="col-auto mt-3 ml-4">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/create.js.erb
<%#= insert error message if an input is missing %>
var errorMessageExist = document.querySelector(".error-message");

if (!errorMessageExist) {
  var errorMessage = '<p class="strong error-message">One or more input are missing.</p>';
  var formCont = document.querySelector("#new-task-form .card");
  formCont.insertAdjacentHTML("beforeend", errorMessage);
}

app/views/tasks/destroy.js.erb
const deleteTask = () => {
  document.querySelector("#task-<%= @task.id %>").remove();
}

deleteTask();

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 col-centered">
      <div class="content">
        <h1 class="title mt-2">ToPoulpe List</h1>
        <p class="small" id="help-link">Need help ?</p>
        <div class="help-cont d-none card">
          <div class="d-flex justify-content-between">
            <p class="small">Click: </p>
            <i class="fas fa-times"></i>
          </div>
            <p class="small"><i class="fas fa-times-circle in-progress"></i> to mark a task as done <i class="fas fa-check-circle done"></i>.</p>
          <p class="small"><i class="fas fa-pen"></i> to edit a task.</p>
          <p class="small"><i class="fas fa-sort-down"></i></i> to read comments and add a new one.</p>
          <p class="small"><i class="fas fa-file-alt"></i> to open the attached file.</p>
          <p class="small m-0"><i class="fas fa-trash"></i></i> to delete a task or a comment.</p>
        </div>
        <button class="btn btn-primary w-100 mb-3" id="new-task-button">
          Add a new task
        </button>
        <div class="d-none" id="new-task-form">
          <% if policy(Task).create? %>
            <%= render "tasks/task_form" %>
          <% end %>
        </div>
        <% if tasks_not_done.zero? %>
        <p class="body">You don't have any task remaining, congrats!</p>
        <% else %>
          <p class="body">You have <strong><%= pluralize(tasks_not_done, "task")%></strong> remaining and <strong><%= pluralize(tasks_due_today, "task") %></strong> due today.</p>
        <% end %>
        <div class="tasks">
          <% @tasks.each do |task| %>
          <div class="task-card card" id="task-<%= task.id %>" >
            <%= render "task", task: task %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/task_error.js.erb
<%#= insert error message if an input is missing %>
var errorMessageExist = document.querySelector(".error-message");

if (!errorMessageExist) {
  var errorMessage = '<p class="strong error-message">One or more input are missing.</p>';
  var formCont = document.querySelector("#new-task-form .card");
  formCont.insertAdjacentHTML("beforeend", errorMessage);
}

app/views/tasks/task_error_create.js.erb
<%#= insert error message if an input is missing %>
var errorMessageExist = document.querySelector(".error-message");

if (!errorMessageExist) {
  var errorMessage = '<p class="strong error-message">One or more input are missing.</p>';
  var formCont = document.querySelector("#new-task-form .card");
  formCont.insertAdjacentHTML("beforeend", errorMessage);
}

app/views/tasks/task_error_update.js.erb
<%#= insert error message if an input is missing %>
var errorMessageExist = document.querySelector(".error-message");

if (!errorMessageExist) {
  var errorMessage = '<p class="strong error-message">One or more input are missing.</p>';
  var formCont = document.querySelector(".edit-form");
  formCont.insertAdjacentHTML("beforeend", errorMessage);
}

app/views/tasks/update.js.erb
function updateTask () {
  var task = document.querySelector(`#task-${"<%= @task.id %>"}`);
  task.innerHTML = ""
  task.innerHTML = "<%= j render "tasks/task", task: @task %>";
}

updateTask();
<%# call those global function to set up the event listeners on the edited task %>
expandCard();
showEditForm();